### PR TITLE
Added ISRG Root X1 for LetsEncrypt

### PR DESCRIPTION
**Pull request by MattyBoy4444**
Added missing root cert

### CODE REVIEW

**Comment by facchinm** [comment]
LGTM!

**Review by aentinger — APPROVED** [review]
LGTM, is identical with the certificate stored [here](https://letsencrypt.org/certs/isrgrootx1.pem).

**Comment by MattyBoy4444** [comment]
Could someone make a release with this new cert?  I can't build my own right now because of other issues.  Thanks.

**Comment by aentinger** [comment]
A new release is coming up by the end of the week.

**Pull request merged**
