### PR TITLE
Downgrade to IDF 3.2.2 as 3.3 is still in beta

### PR DESCRIPTION
**Pull request by sandeepmistry**
Will also replace #26.

### CODE REVIEW

**Comment by facchinm** [comment]
We just need to understand if it fixes the issue with Ubiquity access points. @Rocketct any news on that?

**Comment by Rocketct** [comment]
Tested with v3.2.2 the Ubiquity access points issue is still present.

**Comment by sandeepmistry** [comment]
@Rocketct thanks, could you also please try the `v3.3-beta3` tag?

https://github.com/espressif/esp-idf/releases/tag/v3.3-beta3

**Comment by sandeepmistry** [comment]
I'm closing this, let's track it in https://github.com/arduino/nina-fw/pull/26 instead.

**Pull request closed without merging**
