### PR TITLE
Add reason code command

### PR DESCRIPTION
**Pull request by sandeepmistry**

### CODE REVIEW

**Comment by tigoe** [comment]
how about errorCode()? Does it return all errors or just connection errors?

**Comment by sandeepmistry** [comment]
@tigoe `errorCode()` works for me, as the reason is tied to the disconnect event. Although when a disconnect is requested it's not really an error, but we can filter this out.

Once again, here's the list: https://github.com/espressif/esp-idf/blob/master/docs/en/api-guides/wifi.rst#wi-fi-reason-code

Cisco refers to them as "Deauthentication Reason Codes": https://www.cisco.com/assets/sol/sb/WAP371_Emulators/WAP371_Emulator_v1-0-1-3/help/Apx_ReasonCodes2.html

**Comment by Rocketct** [comment]
tested with a wifi1010 and works for me!!

**Comment by tigoe** [comment]
Oh, I see!  Thanks for the clarification. reasonCode() is good with me then. Sorry, I misunderstood it as all errors.

**Pull request merged**
