### PR TITLE
Ninafw bug fixes

### PR DESCRIPTION
**Pull request by iabdalkader**
### This is a work in progress, submitted for testing & review.

### CODE REVIEW

**Comment by facchinm** [comment]
I merged to allow producing the 1.5.0 artifact for testing, it's not an actual release until we add the binaries to the fw uploader tools

**Comment by JAndrassy** [comment]
I don't understand this PR. What bugs does it fix?

**Comment by iabdalkader** [comment]
> I don't understand this PR. What bugs does it fix?

Perhaps the PR title is a little misleading, however each commit message explains exactly what it's doing. In addition to small bug fixes, and readme update, this adds a new/parallel set of low-level sockets commands.

**Comment by JAndrassy** [comment]
> this adds a new/parallel set of low-level sockets commands.

why?

**Comment by JAndrassy** [comment]
a good PR should solve one problem or add one feature. a 'composite' PR is not good. 
this PR has at many independent changes:
* changes the version number
* adds something to documentation (unrelated to other changes in this PR)
* fixes some compiler warnings
* solves something about WiFiServer by adding parameter port to begin(). what issue does this solve?
* changes ADC_ATTEN_DB_ channel
* adds classic sockets api (without any use of it)

**Pull request merged**
